version: '3'
services:
  auth-center:
    build:
      context: ./auth-center
      dockerfile: Dockerfile
    image: ms-demo/auth-center
    restart: always
    ports:
      - "18080:18080"
    networks:
      - ms-demo-network
    depends_on:
      - auth-center-mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    image: ms-demo/order-service
    restart: always
    ports:
      - "18081:18081"
    networks:
      - ms-demo-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: ms-demo/user-service
    restart: always
    depends_on:
      - user-service-mysql
    ports:
      - "18082:18082"
    networks:
      - ms-demo-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  auth-center-mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - ms-demo-network

  user-service-mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - ms-demo-network

networks:
  ms-demo-network:
