server:
  port: 18082

spring:

  application:
    name: userAuth-service

  # jackson config
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
    serialization:
      indent_output: true
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    #default-property-inclusion: non_empty


  # mysql config
  datasource:
    #url: jdbc:mysql://user-service-mysql:3306/userservie?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/userservie?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # jpa config
  jpa:
   database: MYSQL
   show-sql: true
   hibernate:
     ddl-auto: create-drop
   properties:
     hibernate:
     dialect: org.hibernate.dialect.MySQL5Dialect

  # spring data jpa config
  data:
    jpa:
      repositories.enabled: true

  # rabbitmq config
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest

# log config
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.kylin: DEBUG